# Generated by Django 4.2.5 on 2023-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='complete_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('chunk_number', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('video_chunk', models.FileField(upload_to='video_chunks/')),
            ],
        ),
    ]
